// priority: 0

console.info('Hello, World! (You will see this line every time client resources reload)')

onEvent('rei.group', event => {

  // Wood Groups  
  event.groupItems('kubejs:rei_groups/wooden_planks', 'Wooden Planks', ['architects_palette:twisted_planks','autumnity:maple_planks','ecologics:azalea_planks','ecologics:coconut_planks','ecologics:flowering_azalea_planks','ecologics:walnut_planks','immersive_weathering:charred_planks','minecraft:acacia_planks','minecraft:birch_planks','minecraft:crimson_planks','minecraft:dark_oak_planks','minecraft:jungle_planks','minecraft:oak_planks','minecraft:spruce_planks','minecraft:warped_planks','newworld:fir_planks','twigs:stripped_bamboo_planks','undergarden:grongle_planks','undergarden:smogstem_planks','undergarden:wigglewood_planks','upgrade_aquatic:driftwood_planks','upgrade_aquatic:river_planks','wildbackport:mangrove_planks','atmospheric:rosewood_planks','atmospheric:morado_planks','atmospheric:yucca_planks','atmospheric:kousa_planks','atmospheric:aspen_planks','atmospheric:grimwood_planks','environmental:wisteria_planks','environmental:cherry_planks','environmental:willow_planks']);
  event.groupItems('kubejs:rei_groups/wooden_slabs', 'Wooden Slabs', ['architects_palette:twisted_slab','autumnity:maple_slab','ecologics:azalea_slab','ecologics:coconut_slab','ecologics:flowering_azalea_slab','ecologics:walnut_slab','immersive_weathering:charred_slab','minecraft:acacia_slab','minecraft:birch_slab','minecraft:crimson_slab','minecraft:dark_oak_slab','minecraft:jungle_slab','minecraft:oak_slab','minecraft:spruce_slab','minecraft:warped_slab','newworld:fir_slab','twigs:stripped_bamboo_slab','undergarden:grongle_slab','undergarden:smogstem_slab','undergarden:wigglewood_slab','upgrade_aquatic:driftwood_slab','upgrade_aquatic:river_slab','wildbackport:mangrove_slab','atmospheric:rosewood_slab','atmospheric:morado_slab','atmospheric:yucca_slab','atmospheric:kousa_slab','atmospheric:aspen_slab','atmospheric:grimwood_slab','environmental:wisteria_slab','environmental:cherry_slab','environmental:willow_slab']);
  event.groupItems('kubejs:rei_groups/wooden_stairs', 'Wooden Stairs', ['architects_palette:twisted_stairs','autumnity:maple_stairs','ecologics:azalea_stairs','ecologics:coconut_stairs','ecologics:flowering_azalea_stairs','ecologics:walnut_stairs','immersive_weathering:charred_stairs','minecraft:acacia_stairs','minecraft:birch_stairs','minecraft:crimson_stairs','minecraft:dark_oak_stairs','minecraft:jungle_stairs','minecraft:oak_stairs','minecraft:spruce_stairs','minecraft:warped_stairs','newworld:fir_stairs','twigs:stripped_bamboo_stairs','undergarden:grongle_stairs','undergarden:smogstem_stairs','undergarden:wigglewood_stairs','upgrade_aquatic:driftwood_stairs','upgrade_aquatic:river_stairs','wildbackport:mangrove_stairs','atmospheric:rosewood_stairs','atmospheric:morado_stairs','atmospheric:yucca_stairs','atmospheric:kousa_stairs','atmospheric:aspen_stairs','atmospheric:grimwood_stairs','environmental:wisteria_stairs','environmental:cherry_stairs','environmental:willow_stairs']);
  event.groupItems('kubejs:rei_groups/wooden_fences', 'Wooden Fences', ['architects_palette:twisted_fence','autumnity:maple_fence','ecologics:azalea_fence','ecologics:coconut_fence','ecologics:flowering_azalea_fence','ecologics:walnut_fence','immersive_weathering:charred_fence','minecraft:acacia_fence','minecraft:birch_fence','minecraft:crimson_fence','minecraft:dark_oak_fence','minecraft:jungle_fence','minecraft:oak_fence','minecraft:spruce_fence','minecraft:warped_fence','newworld:fir_fence','twigs:stripped_bamboo_fence','undergarden:grongle_fence','undergarden:smogstem_fence','undergarden:wigglewood_fence','upgrade_aquatic:driftwood_fence','upgrade_aquatic:river_fence','wildbackport:mangrove_fence','atmospheric:rosewood_fence','atmospheric:morado_fence','atmospheric:yucca_fence','atmospheric:kousa_fence','atmospheric:aspen_fence','atmospheric:grimwood_fence','environmental:wisteria_fence','environmental:cherry_fence','environmental:willow_fence']);
  event.groupItems('kubejs:rei_groups/wooden_fence_gates', 'Wooden Fence Gates', ['architects_palette:twisted_fence_gate','autumnity:maple_fence_gate','ecologics:azalea_fence_gate','ecologics:coconut_fence_gate','ecologics:flowering_azalea_fence_gate','ecologics:walnut_fence_gate','immersive_weathering:charred_fence_gate','minecraft:acacia_fence_gate','minecraft:birch_fence_gate','minecraft:crimson_fence_gate','minecraft:dark_oak_fence_gate','minecraft:jungle_fence_gate','minecraft:oak_fence_gate','minecraft:spruce_fence_gate','minecraft:warped_fence_gate','newworld:fir_fence_gate','twigs:stripped_bamboo_fence_gate','undergarden:grongle_fence_gate','undergarden:smogstem_fence_gate','undergarden:wigglewood_fence_gate','upgrade_aquatic:driftwood_fence_gate','upgrade_aquatic:river_fence_gate','wildbackport:mangrove_fence_gate','atmospheric:rosewood_fence_gate','atmospheric:morado_fence_gate','atmospheric:yucca_fence_gate','atmospheric:kousa_fence_gate','atmospheric:aspen_fence_gate','atmospheric:grimwood_fence_gate','environmental:wisteria_fence_gate','environmental:cherry_fence_gate','environmental:willow_fence_gate']);

  event.groupItems('kubejs:rei_groups/wooden_doors', 'Wooden Doors', ['architects_palette:twisted_door','autumnity:maple_door','ecologics:azalea_door','ecologics:coconut_door','ecologics:flowering_azalea_door','ecologics:walnut_door','minecraft:acacia_door','minecraft:birch_door','minecraft:crimson_door','minecraft:dark_oak_door','minecraft:jungle_door','minecraft:oak_door','minecraft:spruce_door','minecraft:warped_door','newworld:fir_door','twigs:stripped_bamboo_door','undergarden:grongle_door','undergarden:smogstem_door','undergarden:wigglewood_door','upgrade_aquatic:driftwood_door','upgrade_aquatic:river_door','wildbackport:mangrove_door','atmospheric:rosewood_door','atmospheric:morado_door','atmospheric:yucca_door','atmospheric:kousa_door','atmospheric:aspen_door','atmospheric:grimwood_door','environmental:wisteria_door','environmental:cherry_door','environmental:willow_door']);
  event.groupItems('kubejs:rei_groups/wooden_trapdoors', 'Wooden Trapdoors', ['architects_palette:twisted_trapdoor','autumnity:maple_trapdoor','ecologics:azalea_trapdoor','ecologics:coconut_trapdoor','ecologics:flowering_azalea_trapdoor','ecologics:walnut_trapdoor','minecraft:acacia_trapdoor','minecraft:birch_trapdoor','minecraft:crimson_trapdoor','minecraft:dark_oak_trapdoor','minecraft:jungle_trapdoor','minecraft:oak_trapdoor','minecraft:spruce_trapdoor','minecraft:warped_trapdoor','newworld:fir_trapdoor','twigs:stripped_bamboo_trapdoor','undergarden:grongle_trapdoor','undergarden:smogstem_trapdoor','undergarden:wigglewood_trapdoor','upgrade_aquatic:driftwood_trapdoor','upgrade_aquatic:river_trapdoor','wildbackport:mangrove_trapdoor','atmospheric:rosewood_trapdoor','atmospheric:morado_trapdoor','atmospheric:yucca_trapdoor','atmospheric:kousa_trapdoor','atmospheric:aspen_trapdoor','atmospheric:grimwood_trapdoor','environmental:wisteria_trapdoor','environmental:cherry_trapdoor','environmental:willow_trapdoor']);
 
  event.groupItems('kubejs:rei_groups/wooden_railings', 'Wooden Railings', ['architects_palette:twisted_railing','everycomp:ap/autumnity/maple_railing','everycomp:ap/ecologics/azalea_railing','everycomp:ap/ecologics/coconut_railing','everycomp:ap/ecologics/flowering_azalea_railing','everycomp:ap/ecologics/walnut_railing','architects_palette:acacia_railing','architects_palette:birch_railing','architects_palette:crimson_railing','architects_palette:dark_oak_railing','architects_palette:jungle_railing','architects_palette:oak_railing','architects_palette:spruce_railing','architects_palette:warped_railing','everycomp:ap/newworld/fir_railing','everycomp:ap/twigs/bamboo_railing','everycomp:ap/undergarden/grongle_railing','everycomp:ap/undergarden/smogstem_railing','everycomp:ap/undergarden/wigglewood_railing','everycomp:ap/upgrade_aquatic/driftwood_railing','everycomp:ap/upgrade_aquatic/river_railing','everycomp:ap/wildbackport/mangrove_railing','everycomp:ap/atmospheric/rosewood_railing','everycomp:ap/atmospheric/morado_railing','everycomp:ap/atmospheric/yucca_railing','everycomp:ap/atmospheric/kousa_railing','everycomp:ap/atmospheric/aspen_railing','everycomp:ap/atmospheric/grimwood_railing','everycomp:ap/environmental/wisteria_railing','everycomp:ap/environmental/cherry_railing','everycomp:ap/environmental/willow_railing']);
  
  event.groupItems('kubejs:rei_groups/wooden_signs', 'Wooden Signs', ['autumnity:maple_sign', 'ecologics:azalea_sign', 'ecologics:coconut_sign', 'ecologics:flowering_azalea_sign', 'ecologics:walnut_sign', 'minecraft:acacia_sign', 'minecraft:birch_sign', 'minecraft:crimson_sign', 'minecraft:dark_oak_sign', 'minecraft:jungle_sign', 'minecraft:oak_sign', 'minecraft:spruce_sign', 'minecraft:warped_sign', 'newworld:fir_sign', 'twigs:stripped_bamboo_sign', 'undergarden:grongle_sign', 'undergarden:smogstem_sign', 'undergarden:wigglewood_sign', 'upgrade_aquatic:driftwood_sign', 'upgrade_aquatic:river_sign', 'wildbackport:mangrove_sign'])

  event.groupItems('kubejs:rei_groups/wooden_buttons', 'Wooden Buttons', ['architects_palette:twisted_button','autumnity:maple_button','ecologics:azalea_button','ecologics:coconut_button','ecologics:walnut_button','minecraft:acacia_button','minecraft:birch_button','minecraft:crimson_button','minecraft:dark_oak_button','minecraft:jungle_button','minecraft:oak_button','minecraft:spruce_button','minecraft:warped_button','newworld:fir_button','twigs:stripped_bamboo_button','undergarden:grongle_button','undergarden:smogstem_button','undergarden:wigglewood_button','upgrade_aquatic:driftwood_button','upgrade_aquatic:river_button','wildbackport:mangrove_button','environmental:wisteria_button','environmental:willow_button','environmental:cherry_button','atmospheric:rosewood_button','atmospheric:morado_button','atmospheric:yucca_button','atmospheric:kousa_button','atmospheric:aspen_button','atmospheric:grimwood_button']);
  event.groupItems('kubejs:rei_groups/pressure_plates', 'Wooden Pressure Plates', ['architects_palette:twisted_pressure_plate','autumnity:maple_pressure_plate','ecologics:azalea_pressure_plate','ecologics:coconut_pressure_plate','ecologics:walnut_pressure_plate','minecraft:acacia_pressure_plate','minecraft:birch_pressure_plate','minecraft:crimson_pressure_plate','minecraft:dark_oak_pressure_plate','minecraft:jungle_pressure_plate','minecraft:oak_pressure_plate','minecraft:spruce_pressure_plate','minecraft:warped_pressure_plate','newworld:fir_pressure_plate','twigs:stripped_bamboo_pressure_plate','undergarden:grongle_pressure_plate','undergarden:smogstem_pressure_plate','undergarden:wigglewood_pressure_plate','upgrade_aquatic:driftwood_pressure_plate','upgrade_aquatic:river_pressure_plate','wildbackport:mangrove_pressure_plate','environmental:wisteria_pressure_plate','environmental:willow_pressure_plate','environmental:cherry_pressure_plate','atmospheric:rosewood_pressure_plate','atmospheric:morado_pressure_plate','atmospheric:yucca_pressure_plate','atmospheric:kousa_pressure_plate','atmospheric:aspen_pressure_plate','atmospheric:grimwood_pressure_plate']);

  event.groupItems('kubejs:rei_groups/wooden_signs', 'Wooden Signs', ['autumnity:maple_sign','ecologics:azalea_sign','ecologics:coconut_sign','ecologics:flowering_azalea_sign','ecologics:walnut_sign','minecraft:acacia_sign','minecraft:birch_sign','minecraft:crimson_sign','minecraft:dark_oak_sign','minecraft:jungle_sign','minecraft:oak_sign','minecraft:spruce_sign','minecraft:warped_sign','newworld:fir_sign','twigs:stripped_bamboo_sign','undergarden:grongle_sign','undergarden:smogstem_sign','undergarden:wigglewood_sign','upgrade_aquatic:driftwood_sign','upgrade_aquatic:river_sign','wildbackport:mangrove_sign','atmospheric:rosewood_sign','atmospheric:morado_sign','atmospheric:yucca_sign','atmospheric:kousa_sign','atmospheric:aspen_sign','atmospheric:grimwood_sign','environmental:wisteria_sign','environmental:cherry_sign','environmental:willow_sign']);

  event.groupItems('kubejs:rei_groups/wooden_boards', 'Wooden Boards', ['autumnity:maple_boards', 'architects_palette:twisted_boards','everycomp:ap/ecologics/azalea_boards','everycomp:ap/ecologics/coconut_boards','everycomp:ap/ecologics/flowering_azalea_boards','everycomp:ap/ecologics/walnut_boards','architects_palette:acacia_boards','architects_palette:birch_boards','architects_palette:crimson_boards','architects_palette:dark_oak_boards','architects_palette:jungle_boards','architects_palette:oak_boards','architects_palette:spruce_boards','architects_palette:warped_boards','everycomp:ap/newworld/fir_boards','everycomp:ap/twigs/bamboo_boards','everycomp:ap/undergarden/grongle_boards','everycomp:ap/undergarden/smogstem_boards','everycomp:ap/undergarden/wigglewood_boards','everycomp:ap/wildbackport/mangrove_boards','atmospheric:rosewood_boards','atmospheric:morado_boards','atmospheric:yucca_boards','atmospheric:kousa_boards','atmospheric:aspen_boards','atmospheric:grimwood_boards','environmental:wisteria_boards','environmental:cherry_boards','environmental:willow_boards']);

  event.groupItems('kubejs:rei_groups/boats', 'Boats', ['autumnity:maple_boat','ecologics:azalea_boat','ecologics:coconut_boat','ecologics:flowering_azalea_boat','ecologics:walnut_boat','minecraft:acacia_boat','minecraft:birch_boat','minecraft:dark_oak_boat','minecraft:jungle_boat','minecraft:oak_boat','minecraft:spruce_boat','newworld:fir_boat','twigs:stripped_bamboo_boat','undergarden:grongle_boat','undergarden:smogstem_boat','undergarden:wigglewood_boat','upgrade_aquatic:driftwood_boat','upgrade_aquatic:river_boat','wildbackport:mangrove_boat','atmospheric:rosewood_boat','atmospheric:morado_boat','atmospheric:yucca_boat','atmospheric:kousa_boat','atmospheric:aspen_boat','atmospheric:grimwood_boat','environmental:wisteria_boat','environmental:cherry_boat','environmental:willow_boat']);

  event.groupItems('kubejs:rei_groups/saplings', 'Saplings', ['architects_palette:twisted_sapling','autumnity:maple_sapling','autumnity:orange_maple_sapling','autumnity:red_maple_sapling','autumnity:yellow_maple_sapling','ecologics:azalea_flower','ecologics:coconut_seedling','ecologics:walnut_sapling','minecraft:acacia_sapling','minecraft:azalea','minecraft:birch_sapling','minecraft:dark_oak_sapling','minecraft:flowering_azalea','minecraft:jungle_sapling','minecraft:oak_sapling','minecraft:spruce_sapling','newworld:fir_sapling','undergarden:grongle_sapling','undergarden:smogstem_sapling','undergarden:wigglewood_sapling','upgrade_aquatic:river_sapling','wildbackport:mangrove_sapling','environmental:pink_wisteria_sapling','environmental:blue_wisteria_sapling','environmental:white_wisteria_sapling','environmental:purple_wisteria_sapling','environmental:willow_sapling','environmental:cherry_sapling','atmospheric:rosewood_sapling','atmospheric:morado_sapling','atmospheric:yucca_sapling','atmospheric:kousa_sapling','atmospheric:aspen_sapling','atmospheric:grimwood_sapling']);

  event.groupItems('kubejs:rei_groups/stripped_logs', 'Stripped Logs', ['architects_palette:stripped_twisted_log','autumnity:sappy_maple_log','autumnity:stripped_maple_log','ecologics:stripped_azalea_log','ecologics:stripped_coconut_log','ecologics:stripped_flowering_azalea_log','ecologics:stripped_walnut_log','minecraft:stripped_acacia_log','minecraft:stripped_birch_log','minecraft:stripped_crimson_stem','minecraft:stripped_dark_oak_log','minecraft:stripped_jungle_log','minecraft:stripped_oak_log','minecraft:stripped_spruce_log','minecraft:stripped_warped_stem','newworld:stripped_fir_log','undergarden:stripped_grongle_log','undergarden:stripped_smogstem_log','undergarden:stripped_wigglewood_log','upgrade_aquatic:stripped_driftwood_log','upgrade_aquatic:stripped_river_log','wildbackport:stripped_mangrove_log','environmental:stripped_wisteria_log','environmental:stripped_willow_log','environmental:stripped_cherry_log','atmospheric:stripped_rosewood_log','atmospheric:stripped_morado_log','atmospheric:stripped_yucca_log','atmospheric:stripped_kousa_log','atmospheric:stripped_aspen_log','atmospheric:stripped_grimwood_log']);
  event.groupItems('kubejs:rei_groups/wood', 'Wood Blocks', ['architects_palette:twisted_wood','autumnity:maple_wood','ecologics:azalea_wood','ecologics:coconut_wood','ecologics:flowering_azalea_wood','ecologics:walnut_wood','minecraft:acacia_wood','minecraft:birch_wood','minecraft:crimson_hyphae','minecraft:dark_oak_wood','minecraft:jungle_wood','minecraft:oak_wood','minecraft:spruce_wood','minecraft:warped_hyphae','newworld:fir_wood','undergarden:grongle_wood','undergarden:smogstem_wood','undergarden:wigglewood_wood','upgrade_aquatic:driftwood','upgrade_aquatic:river_wood','wildbackport:mangrove_wood','atmospheric:rosewood_wood','atmospheric:morado_wood','atmospheric:yucca_wood','atmospheric:kousa_wood','atmospheric:aspen_wood','atmospheric:grimwood_wood','environmental:wisteria_wood','environmental:willow_wood','environmental:cherry_wood']);
  event.groupItems('kubejs:rei_groups/stripped_wood', 'Stripped Wood Blocks', ['architects_palette:stripped_twisted_wood','autumnity:stripped_maple_wood','ecologics:stripped_azalea_wood','ecologics:stripped_coconut_wood','ecologics:stripped_flowering_azalea_wood','ecologics:stripped_walnut_wood','minecraft:stripped_acacia_wood','minecraft:stripped_birch_wood','minecraft:stripped_crimson_hyphae','minecraft:stripped_dark_oak_wood','minecraft:stripped_jungle_wood','minecraft:stripped_oak_wood','minecraft:stripped_spruce_wood','minecraft:stripped_warped_hyphae','newworld:stripped_fir_wood','undergarden:stripped_grongle_wood','undergarden:stripped_smogstem_wood','undergarden:stripped_wigglewood_wood','upgrade_aquatic:stripped_driftwood','upgrade_aquatic:stripped_river_wood','wildbackport:stripped_mangrove_wood','environmental:stripped_wisteria_wood','environmental:stripped_willow_wood','environmental:stripped_cherry_wood','atmospheric:stripped_rosewood_wood','atmospheric:stripped_morado_wood','atmospheric:stripped_yucca_wood','atmospheric:stripped_kousa_wood','atmospheric:stripped_aspen_wood','atmospheric:stripped_grimwood_wood']);
  event.groupItems('kubejs:rei_groups/logs', 'Logs', ['architects_palette:twisted_log','autumnity:maple_log','ecologics:azalea_log','ecologics:coconut_log','ecologics:flowering_azalea_log','ecologics:walnut_log','immersive_weathering:charred_log','minecraft:acacia_log','minecraft:birch_log','minecraft:crimson_stem','minecraft:dark_oak_log','minecraft:jungle_log','minecraft:oak_log','minecraft:spruce_log','minecraft:warped_stem','newworld:fir_log','undergarden:grongle_log','undergarden:smogstem_log','undergarden:wigglewood_log','upgrade_aquatic:driftwood_log','upgrade_aquatic:river_log','wildbackport:mangrove_log','atmospheric:rosewood_log','atmospheric:morado_log','atmospheric:yucca_log','atmospheric:kousa_log','atmospheric:aspen_log','atmospheric:grimwood_log','environmental:wisteria_log','environmental:willow_log','environmental:cherry_log']);

  event.groupItems('kubejs:rei_groups/wooden_ladders', 'Wooden Ladders', ['autumnity:maple_ladder','everycomp:q/architects_palette/twisted_ladder','everycomp:q/ecologics/azalea_ladder','everycomp:q/ecologics/coconut_ladder','everycomp:q/ecologics/flowering_azalea_ladder','everycomp:q/ecologics/walnut_ladder','everycomp:q/newworld/fir_ladder','everycomp:q/twigs/bamboo_ladder','everycomp:q/undergarden/grongle_ladder','everycomp:q/undergarden/smogstem_ladder','everycomp:q/undergarden/wigglewood_ladder','minecraft:ladder','quark:acacia_ladder','quark:birch_ladder','quark:crimson_ladder','quark:dark_oak_ladder','quark:jungle_ladder','quark:spruce_ladder','quark:warped_ladder','upgrade_aquatic:driftwood_ladder','upgrade_aquatic:river_ladder','everycomp:q/wildbackport/mangrove_ladder','atmospheric:kousa_ladder','atmospheric:grimwood_ladder','atmospheric:morado_ladder','atmospheric:rosewood_ladder','atmospheric:aspen_ladder','atmospheric:yucca_ladder','environmental:cherry_ladder','environmental:wisteria_ladder','environmental:willow_ladder']);
  event.groupItems('kubejs:rei_groups/wooden_chests', 'Wooden Chests', ['autumnity:maple_chest', 'carpenter:acacia_chest', 'carpenter:birch_chest', 'carpenter:crimson_chest', 'carpenter:dark_oak_chest', 'carpenter:jungle_chest', 'carpenter:oak_chest', 'carpenter:spruce_chest', 'carpenter:warped_chest', 'everycomp:q/architects_palette/twisted_chest', 'everycomp:q/ecologics/azalea_chest', 'everycomp:q/ecologics/coconut_chest', 'everycomp:q/ecologics/flowering_azalea_chest', 'everycomp:q/ecologics/walnut_chest', 'everycomp:q/newworld/fir_chest', 'everycomp:q/twigs/bamboo_chest', 'everycomp:q/undergarden/grongle_chest', 'everycomp:q/undergarden/smogstem_chest', 'everycomp:q/undergarden/wigglewood_chest', 'everycomp:q/wildbackport/mangrove_chest', 'upgrade_aquatic:driftwood_chest', 'upgrade_aquatic:river_chest', 'atmospheric:rosewood_chest', 'atmospheric:morado_chest', 'atmospheric:yucca_chest', 'atmospheric:kousa_chest', 'atmospheric:aspen_chest', 'atmospheric:grimwood_chest', 'environmental:cherry_chest', 'environmental:wisteria_chest', 'environmental:willow_chest']);
  event.groupItems('kubejs:rei_groups/wooden_bookshelves', 'Bookshelves', ['autumnity:maple_bookshelf','carpenter:acacia_bookshelf','carpenter:birch_bookshelf','carpenter:crimson_bookshelf','carpenter:dark_oak_bookshelf','carpenter:jungle_bookshelf','carpenter:spruce_bookshelf','carpenter:warped_bookshelf','everycomp:q/architects_palette/twisted_bookshelf','everycomp:q/ecologics/azalea_bookshelf','everycomp:q/ecologics/coconut_bookshelf','everycomp:q/ecologics/flowering_azalea_bookshelf','everycomp:q/ecologics/walnut_bookshelf','newworld:fir_bookshelf','everycomp:q/twigs/bamboo_bookshelf','everycomp:q/undergarden/grongle_bookshelf','everycomp:q/undergarden/smogstem_bookshelf','everycomp:q/undergarden/wigglewood_bookshelf','everycomp:q/wildbackport/mangrove_bookshelf','minecraft:bookshelf','upgrade_aquatic:driftwood_bookshelf','upgrade_aquatic:river_bookshelf','environmental:cherry_bookshelf','environmental:wisteria_bookshelf','environmental:willow_bookshelf','atmospheric:rosewood_bookshelf','atmospheric:morado_bookshelf','atmospheric:yucca_bookshelf','atmospheric:kousa_bookshelf','atmospheric:aspen_bookshelf','atmospheric:grimwood_bookshelf']);
  event.groupItems('kubejs:rei_groups/windows', 'Windows', ['create:acacia_window','create:birch_window','create:crimson_window','create:dark_oak_window','create:jungle_window','create:oak_window','create:ornate_iron_window','create:spruce_window','create:warped_window','everycomp:c/architects_palette/twisted_window','everycomp:c/autumnity/maple_window','everycomp:c/ecologics/azalea_window','everycomp:c/ecologics/coconut_window','everycomp:c/ecologics/flowering_azalea_window','everycomp:c/ecologics/walnut_window','everycomp:c/newworld/fir_window','everycomp:c/twigs/bamboo_window','everycomp:c/undergarden/grongle_window','everycomp:c/undergarden/smogstem_window','everycomp:c/undergarden/wigglewood_window','everycomp:c/wildbackport/mangrove_window','everycomp:c/upgrade_aquatic/driftwood_window','everycomp:c/upgrade_aquatic/river_window','everycomp:c/environmental/cherry_window','everycomp:c/environmental/wisteria_window','everycomp:c/environmental/willow_window','everycomp:c/atmospheric/rosewood_window','everycomp:c/atmospheric/morado_window','everycomp:c/atmospheric/yucca_window','everycomp:c/atmospheric/kousa_window','everycomp:c/atmospheric/aspen_window','everycomp:c/atmospheric/grimwood_window']);
  event.groupItems('kubejs:rei_groups/window_panes', 'Window Panes', ['create:acacia_window_pane','create:birch_window_pane','create:crimson_window_pane','create:dark_oak_window_pane','create:jungle_window_pane','create:oak_window_pane','create:ornate_iron_window_pane','create:spruce_window_pane','create:warped_window_pane','everycomp:c/architects_palette/twisted_window_pane','everycomp:c/autumnity/maple_window_pane','everycomp:c/ecologics/azalea_window_pane','everycomp:c/ecologics/coconut_window_pane','everycomp:c/ecologics/flowering_azalea_window_pane','everycomp:c/ecologics/walnut_window_pane','everycomp:c/newworld/fir_window_pane','everycomp:c/twigs/bamboo_window_pane','everycomp:c/undergarden/grongle_window_pane','everycomp:c/undergarden/smogstem_window_pane','everycomp:c/undergarden/wigglewood_window_pane','everycomp:c/wildbackport/mangrove_window_pane','everycomp:c/upgrade_aquatic/driftwood_window_pane','everycomp:c/upgrade_aquatic/river_window_pane','everycomp:c/environmental/cherry_window_pane','everycomp:c/environmental/wisteria_window_pane','everycomp:c/environmental/willow_window_pane','everycomp:c/atmospheric/rosewood_window_pane','everycomp:c/atmospheric/morado_window_pane','everycomp:c/atmospheric/yucca_window_pane','everycomp:c/atmospheric/kousa_window_pane','everycomp:c/atmospheric/aspen_window_pane','everycomp:c/atmospheric/grimwood_window_pane']);
  event.groupItems('kubejs:rei_groups/leaves', 'Leaves', ['architects_palette:twisted_leaves', 'autumnity:maple_leaves', 'autumnity:orange_maple_leaves', 'autumnity:red_maple_leaves', 'autumnity:yellow_maple_leaves', 'ecologics:coconut_leaves', 'ecologics:walnut_leaves', 'minecraft:acacia_leaves', 'minecraft:azalea_leaves', 'minecraft:birch_leaves', 'minecraft:dark_oak_leaves', 'minecraft:flowering_azalea_leaves', 'minecraft:jungle_leaves', 'minecraft:oak_leaves', 'minecraft:spruce_leaves', 'newworld:fir_leaves', 'undergarden:grongle_leaves', 'undergarden:smogstem_leaves', 'undergarden:wigglewood_leaves', 'upgrade_aquatic:river_leaves', 'wildbackport:mangrove_leaves','environmental:white_wisteria_leaves','environmental:blue_wisteria_leaves','environmental:pink_wisteria_leaves','environmental:purple_wisteria_leaves','environmental:willow_leaves','environmental:cherry_leaves','atmospheric:rosewood_leaves','atmospheric:morado_leaves','atmospheric:flowering_morado_leaves','atmospheric:yucca_leaves','atmospheric:kousa_leaves','atmospheric:aspen_leaves','atmospheric:grimwood_leaves'])

  event.groupItems('kubejs:rei_groups/sleds', 'Sleds', ['#snowyspirit:sleds'])
  event.groupItems('kubejs:rei_groups/hanging_signs', 'Hanging Signs', ['#supplementaries:hanging_signs'])
  event.groupItems('kubejs:rei_groups/sign_posts', 'Sign Posts', ['#supplementaries:sign_posts'])
  event.groupItems('kubejs:rei_groups/cabinets', 'Cabinets', ['#farmersdelight:cabinets'])
  event.groupItems('kubejs:rei_groups/leaf_piles', 'Leaf Piles', ['#immersive_weathering:leaf_piles'])
  event.groupItems('kubejs:rei_groups/tables', 'Tables', ['#twigs:tables'])

  // 16-Colored Items
  event.groupItems('kubejs:rei_groups/wool', 'Wool', ['#minecraft:wool'])
  event.groupItems('kubejs:rei_groups/elevators', 'Elevators', ['#elevatorid:elevators'])
  event.groupItems('kubejs:rei_groups/glazed_terracotta', 'Glazed Terracotta', ['/minecraft:.*glazed_terracotta/'])
  event.groupItems('kubejs:rei_groups/wool', 'Wool', ['#minecraft:wool'])
  event.groupItems('kubejs:rei_groups/terracotta', 'Terracotta', ['#minecraft:terracotta'])
  event.groupItems('kubejs:rei_groups/wool_carpets', 'Wool Carpets', ['#mekanism:colorable/carpets'])
  event.groupItems('kubejs:rei_groups/stained_glass', 'Stained Glass', ['#forge:stained_glass'])
  event.groupItems('kubejs:rei_groups/stained_glass_panes', 'Stained Glass Panes', ['#forge:stained_glass_panes'])
  event.groupItems('kubejs:rei_groups/shulker_boxes', 'Shulker Boxes', ['#forge:shulker_boxes'])
  event.groupItems('kubejs:rei_groups/concrete', 'Concrete', ['#forge:concrete'])
  event.groupItems('kubejs:rei_groups/concrete_powder', 'Concrete Powder', ['#forge:concrete_powders'])
  event.groupItems('kubejs:rei_groups/beds', 'Beds', ['#minecraft:beds'])
  event.groupItems('kubejs:rei_groups/banners', 'Banners', ['#minecraft:banners'])
  event.groupItems('kubejs:rei_groups/candles', 'Candles', ['#minecraft:candles'])
  event.groupItems('kubejs:rei_groups/runes', 'Runes', ['/quark:.*_rune/'])
  event.groupItems('kubejs:rei_groups/framed_glass', 'Framed Glass', ['/quark:.*framed_glass/'])
  event.groupItems('kubejs:rei_groups/framed_glass_panes', 'Framed Glass Panes', ['/quark:.*framed_glass_pane.*/'])
  event.groupItems('kubejs:rei_groups/pet_beds', 'Pet Beds', ['/domesticationinnovation:.*pet_bed.*/'])
  event.groupItems('kubejs:rei_groups/bedrolls', 'Bedrolls', ['/druidcraftrg:.*bedroll.*/'])
  event.groupItems('kubejs:rei_groups/gumdrops', 'Gumdrops', ['#snowyspirit:gumdrops'])
  event.groupItems('kubejs:rei_groups/glow_lights', 'Glow Lights', ['#snowyspirit:glow_lights'])
  event.groupItems('kubejs:rei_groups/valve_handles', 'Valve Handles', ['#create:valve_handles'])
  event.groupItems('kubejs:rei_groups/seats', 'Seats', ['#create:seats'])
  event.groupItems('kubejs:rei_groups/toolboxes', 'Toolboxes', ['#create:toolboxes'])
  event.groupItems('kubejs:rei_groups/flags', 'Flags', ['#supplementaries:flags'])
  event.groupItems('kubejs:rei_groups/candle_holders', 'Candle Holders', ['#supplementaries:candle_holders'])
  event.groupItems('kubejs:rei_groups/chalk', 'Chalk', ['#chalk:chalk'])
  event.groupItems('kubejs:rei_groups/presents', 'Presents', ['#supplementaries:presents'])
  event.groupItems('kubejs:rei_groups/canvas_signs', 'Canvas Signs', ['#farmersdelight:canvas_signs'])
  event.groupItems('kubejs:rei_groups/neon_lights', 'Neon Lights', ['/dustrial_decor:.*neon_light/'])
  event.groupItems('kubejs:rei_groups/chiseled_terracotta_bricks', 'Chiseled Terracotta Bricks', ['/clayworks:chiseled.*_terracotta_bricks/'])
  event.groupItems('kubejs:rei_groups/terracotta_bricks', 'Terracotta Bricks', ['clayworks:terracotta_bricks',
  'clayworks:white_terracotta_bricks', 'clayworks:orange_terracotta_bricks', 'clayworks:magenta_terracotta_bricks',
  'clayworks:light_blue_terracotta_bricks', 'clayworks:yellow_terracotta_bricks', 'clayworks:lime_terracotta_bricks',
  'clayworks:pink_terracotta_bricks', 'clayworks:gray_terracotta_bricks', 'clayworks:light_gray_terracotta_bricks',
  'clayworks:cyan_terracotta_bricks', 'clayworks:purple_terracotta_bricks', 'clayworks:blue_terracotta_bricks',
  'clayworks:brown_terracotta_bricks', 'clayworks:green_terracotta_bricks', 'clayworks:red_terracotta_bricks',
  'clayworks:black_terracotta_bricks'])
  event.groupItems('kubejs:rei_groups/coral_blocks', 'Coral Blocks', ["minecraft:bubble_coral_block",
  "upgrade_aquatic:acan_coral_block","minecraft:tube_coral_block","minecraft:horn_coral_block",
  "minecraft:brain_coral_block","minecraft:fire_coral_block",
  "upgrade_aquatic:finger_coral_block","upgrade_aquatic:star_coral_block","upgrade_aquatic:moss_coral_block",
  "upgrade_aquatic:petal_coral_block","upgrade_aquatic:branch_coral_block","upgrade_aquatic:rock_coral_block",
  "upgrade_aquatic:pillow_coral_block","upgrade_aquatic:silk_coral_block","upgrade_aquatic:chrome_coral_block",
  "upgrade_aquatic:prismarine_coral_block"])
  event.groupItems('kubejs:rei_groups/dead_coral_blocks', 'Dead Coral Blocks', ["minecraft:dead_bubble_coral_block",
  "upgrade_aquatic:dead_acan_coral_block","minecraft:dead_tube_coral_block","minecraft:dead_horn_coral_block",
  "minecraft:dead_brain_coral_block","minecraft:dead_fire_coral_block",
  "upgrade_aquatic:dead_finger_coral_block","upgrade_aquatic:dead_star_coral_block","upgrade_aquatic:dead_moss_coral_block",
  "upgrade_aquatic:dead_petal_coral_block","upgrade_aquatic:dead_branch_coral_block","upgrade_aquatic:dead_rock_coral_block",
  "upgrade_aquatic:dead_pillow_coral_block","upgrade_aquatic:dead_silk_coral_block","upgrade_aquatic:dead_chrome_coral_block",
  "upgrade_aquatic:elder_prismarine_coral_block"])
  event.groupItems('kubejs:rei_groups/dead_coral_fans', 'Dead Coral Fans', ["minecraft:dead_bubble_coral_fan",
  "upgrade_aquatic:dead_acan_coral_fan","minecraft:dead_tube_coral_fan","minecraft:dead_horn_coral_fan",
  "minecraft:dead_brain_coral_fan","minecraft:dead_fire_coral_fan",
  "upgrade_aquatic:dead_finger_coral_fan","upgrade_aquatic:dead_star_coral_fan","upgrade_aquatic:dead_moss_coral_fan",
  "upgrade_aquatic:dead_petal_coral_fan","upgrade_aquatic:dead_branch_coral_fan","upgrade_aquatic:dead_rock_coral_fan",
  "upgrade_aquatic:dead_pillow_coral_fan","upgrade_aquatic:dead_silk_coral_fan","upgrade_aquatic:dead_chrome_coral_fan",
  "upgrade_aquatic:elder_prismarine_coral_fan"])
  event.groupItems('kubejs:rei_groups/dead_coral_plants', 'Dead Corals', ["minecraft:dead_bubble_coral",
  "upgrade_aquatic:dead_acan_coral","minecraft:dead_tube_coral","minecraft:dead_horn_coral",
  "minecraft:dead_brain_coral","minecraft:dead_fire_coral",
  "upgrade_aquatic:dead_finger_coral","upgrade_aquatic:dead_star_coral","upgrade_aquatic:dead_moss_coral",
  "upgrade_aquatic:dead_petal_coral","upgrade_aquatic:dead_branch_coral","upgrade_aquatic:dead_rock_coral",
  "upgrade_aquatic:dead_pillow_coral","upgrade_aquatic:dead_silk_coral","upgrade_aquatic:dead_chrome_coral",
  "upgrade_aquatic:elder_prismarine_coral"])
  event.groupItems('kubejs:rei_groups/coral_plants', 'Corals', ['minecraft:bubble_coral',
  'minecraft:tube_coral','minecraft:horn_coral','minecraft:brain_coral','minecraft:fire_coral',
  'upgrade_aquatic:acan_coral','upgrade_aquatic:finger_coral','upgrade_aquatic:star_coral',
  'upgrade_aquatic:moss_coral','upgrade_aquatic:petal_coral','upgrade_aquatic:branch_coral',
  'upgrade_aquatic:rock_coral','upgrade_aquatic:silk_coral','upgrade_aquatic:chrome_coral',
  'upgrade_aquatic:prismarine_coral','upgrade_aquatic:pillow_coral'])
  event.groupItems('kubejs:rei_groups/coral_fans', 'Coral Fans', ['minecraft:bubble_coral_fan',
  'minecraft:tube_coral_fan','minecraft:horn_coral_fan','minecraft:brain_coral_fan','minecraft:fire_coral_fan',
  'upgrade_aquatic:acan_coral_fan','upgrade_aquatic:finger_coral_fan','upgrade_aquatic:star_coral_fan',
  'upgrade_aquatic:moss_coral_fan','upgrade_aquatic:petal_coral_fan','upgrade_aquatic:branch_coral_fan',
  'upgrade_aquatic:rock_coral_fan','upgrade_aquatic:silk_coral_fan','upgrade_aquatic:chrome_coral_fan',
  'upgrade_aquatic:prismarine_coral_fan','upgrade_aquatic:pillow_coral_fan'])
  event.groupItems('kubejs:rei_groups/coralstone', 'Coralstone', ['upgrade_aquatic:coralstone','upgrade_aquatic:bubble_coralstone',
  'upgrade_aquatic:tube_coralstone','upgrade_aquatic:horn_coralstone','upgrade_aquatic:brain_coralstone','upgrade_aquatic:fire_coralstone',
  'upgrade_aquatic:acan_coralstone','upgrade_aquatic:finger_coralstone','upgrade_aquatic:star_coralstone','upgrade_aquatic:moss_coralstone',
  'upgrade_aquatic:petal_coralstone','upgrade_aquatic:branch_coralstone','upgrade_aquatic:rock_coralstone','upgrade_aquatic:pillow_coralstone',
  'upgrade_aquatic:silk_coralstone','upgrade_aquatic:chrome_coralstone','upgrade_aquatic:prismarine_coralstone',
  'upgrade_aquatic:elder_prismarine_coralstone','upgrade_aquatic:dead_coralstone'])
  event.groupItems('kubejs:rei_groups/chiseled_coralstone', 'Chiseled Coralstone', ['/upgrade_aquatic:chiseled_.*coralstone/'])

  const useNbt = ['potion', 'enchanted_book', 'splash_potion', 'tipped_arrow', 'lingering_potion']

  useNbt.forEach(id => {
    const item = Item.of(id)
    const { namespace, path } = Utils.id(item.id)
    event.groupSameItem(`kubejs:rei_groups/${namespace}/${path}`, item.name, item)
  })
  const qNbt = ['ancient_tome', 'seed_pouch']

  qNbt.forEach(id => {
    const item = Item.of(id)
    const { namespace, path } = Utils.id(item.id)
    event.groupItems(`kubejs:rei_groups/${namespace}/${path}`, item.name, item)
  })

  event.groupItems('kubejs:rei_groups/spawn_eggs', 'Spawn Eggs', [
    /spawn_egg/
  ])

  })
