
[General]
	#Should wind be displayed?
	#Default: true
	should_display_wind = true
	#Wind Frequency for: Forest, Taiga, and Desert biomes
	#Default: 0.025
	#Range: 0.0 ~ 5.0
	low_wind_frequency = 0.025
	#Wind Frequency for: Plains and Savanna biomes
	#Default: 0.05
	#Range: 0.0 ~ 5.0
	medium_wind_frequency = 0.05
	#Wind Frequency for: Icy, Extreme Hills, and Mountain biomes
	#Default: 0.075
	#Range: 0.0 ~ 5.0
	high_wind_frequency = 0.075

