
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Allows the mod to try to remap and convert other blocks and items from other compat mods that have been uninstalled from one world. This was made so one can uninstall such mods seamlessly having their blocks converted into Evety Compat counterparts
	remap_other_mods = false
	#Clears out and remaps all blocks registered by this mod belonging to uninstalled wood types to air or oak wood
	remap_self = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true

[leaves_type]

	[leaves_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		azalea = true
		flowering_azalea = true

	[leaves_type.twigs]
		bamboo = true

	[leaves_type.architects_palette]
		twisted = true

	[leaves_type.ecologics]
		coconut = true
		walnut = true

	[leaves_type.undergarden]
		smogstem = true
		wigglewood = true
		grongle = true

	[leaves_type.quark]
		blue_blossom = false
		lavender_blossom = false
		orange_blossom = false
		pink_blossom = false
		yellow_blossom = false
		red_blossom = false

	[leaves_type.upgrade_aquatic]
		river = true

	[leaves_type.autumnity]
		maple = true
		yellow_maple = true
		orange_maple = true
		red_maple = true

	[leaves_type.environmental]
		willow = true
		cherry = true

	[leaves_type.atmospheric]
		rosewood = true
		morado = true
		yucca = true
		kousa = true
		aspen = true
		grimwood = true
		flowering_morado = true

	[leaves_type.wildbackport]
		mangrove = true

	[leaves_type.newworld]
		fir = true

[wood_type]

	[wood_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		crimson = true
		warped = true

	[wood_type.twigs]
		bamboo = true

	[wood_type.ecologics]
		flowering_azalea = true
		coconut = true
		walnut = true
		azalea = true

	[wood_type.architects_palette]
		twisted = true

	[wood_type.quark]
		azalea = false
		blossom = false

	[wood_type.undergarden]
		smogstem = true
		wigglewood = true
		grongle = true

	[wood_type.habitat]
		fairy_ring_mushroom = false

	[wood_type.upgrade_aquatic]
		driftwood = true
		river = true

	[wood_type.autumnity]
		maple = true

	[wood_type.environmental]
		willow = true
		cherry = true
		wisteria = true

	[wood_type.atmospheric]
		rosewood = true
		morado = true
		yucca = true
		kousa = true
		aspen = true
		grimwood = true

	[wood_type.wildbackport]
		mangrove = true

	[wood_type.newworld]
		fir = true

